version: "3.9"

services:
  airflow-init:
    build: .
    container_name: airflow-init
    entrypoint: >
      bash -c "
        python -m airflow db init &&
        python -m airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./notebooks:/opt/airflow/notebooks
      - airflow_db:/opt/airflow 
      - ./data:/opt/airflow/data # Shared volume
    environment:
      - AIRFLOW_HOME=/opt/airflow

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    command: ["python", "-m", "airflow", "webserver"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./notebooks:/opt/airflow/notebooks
      - airflow_db:/opt/airflow
      - ./data:/opt/airflow/data  # Shared volume
    environment:
      - AIRFLOW_HOME=/opt/airflow

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    command: ["python", "-m", "airflow", "scheduler"]
    restart: always
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./notebooks:/opt/airflow/notebooks
      - airflow_db:/opt/airflow 
      - ./data:/opt/airflow/data # Shared volume
    environment:
      - AIRFLOW_HOME=/opt/airflow
    



  superset:
    image: apache/superset:3.0.0
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=my_superset_key
    volumes:
      - superset_home:/app/superset_home

    depends_on:
      - airflow-webserver  
    restart: always
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: retail_db
      MYSQL_USER: airflow_user
      MYSQL_PASSWORD: airflow_pass
    ports:
      - "3306:3306"
    volumes:
      - ./warehouse:/var/lib/mysql


volumes:
  airflow_db:  # Declare named volume
  superset_home:
