FROM python:3.9-slim

ENV AIRFLOW_HOME=/opt/airflow

# System dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    curl \
    git \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Set workdir
WORKDIR $AIRFLOW_HOME

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
RUN pip install mysql-connector-python
# Set PATH
ENV PATH="$AIRFLOW_HOME/bin:$PATH"

# Create folders
RUN mkdir -p $AIRFLOW_HOME/dags $AIRFLOW_HOME/logs $AIRFLOW_HOME/plugins \
    && mkdir -p $AIRFLOW_HOME/scripts $AIRFLOW_HOME/notebooks

# Copy project files
COPY ./dags $AIRFLOW_HOME/dags
COPY ./scripts $AIRFLOW_HOME/scripts
COPY ./notebooks $AIRFLOW_HOME/notebooks

# Run webserver by default
CMD ["airflow", "webserver"]
